title: "Jens Spahn MdB"
permalink: "pretty"
encoding: "utf-8"
description: "Write an awesome description for your new site here."

baseurl: ""
url: "https://stefankp.github.io/jensspahn/"

twitter_username: "jensspahn"
fasebook_username: "jensspahn"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
